// Run only against the isolated in-memory database created below.
// deno run --node-modules-dir=none --allow-read --allow-env supabase/tests/apple-billing.mjs
import {PGlite} from 'npm:@electric-sql/pglite@0.5.8';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role; CREATE SCHEMA auth;
CREATE FUNCTION auth.role() RETURNS text LANGUAGE sql AS $$ SELECT current_setting('request.jwt.claim.role',true) $$;
CREATE TABLE public.profiles(user_id uuid PRIMARY KEY,preferences jsonb DEFAULT '{}', premium_expires_at timestamptz, is_lifetime_premium boolean DEFAULT false, subscription_status text DEFAULT 'free', stripe_customer_id text);
GRANT USAGE ON SCHEMA public,auth TO authenticated,service_role;
GRANT ALL ON public.profiles TO authenticated,service_role;
GRANT EXECUTE ON FUNCTION auth.role() TO authenticated,service_role;`);
await db.exec(await readFile(new URL('../migrations/20260907000954_secure_apple_iap_entitlements.sql', import.meta.url),'utf8'));
const id='11111111-1111-4111-8111-111111111111';
await db.query('INSERT INTO profiles(user_id,preferences) VALUES ($1,$2)',[id,{theme:'green'}]);
const future=n=>new Date(Date.now()+n*86400000).toISOString();
const state={verified:true,environment:'Production',product_id:'se.honsgarden.plus.monthly',original_transaction_id:'orig',transaction_id:'t1',signed_at:future(-1),expires_at:future(30),revoked_at:null};
await db.exec(`SET ROLE authenticated; SELECT set_config('request.jwt.claim.role','authenticated',false);`);
await db.query('UPDATE profiles SET preferences=$1 WHERE user_id=$2',[{theme:'blue',apple_iap:state},id]);
assert.deepEqual((await db.query('SELECT preferences FROM profiles')).rows[0].preferences,{theme:'blue'});
await assert.rejects(()=>db.query('SELECT apply_apple_iap_entitlement($1,$2)',[id,state]),/permission denied/);
await db.exec(`RESET ROLE; SET ROLE service_role; SELECT set_config('request.jwt.claim.role','service_role',false);`);
const apply=async s=>(await db.query('SELECT apply_apple_iap_entitlement($1,$2) result',[id,s])).rows[0].result;
assert.equal((await apply(state)).subscribed,true);
assert.equal((await db.query('SELECT preferences FROM profiles')).rows[0].preferences.theme,'blue');
const renewal={...state,transaction_id:'t2',signed_at:future(0),expires_at:future(60)};
assert.equal((await apply(renewal)).subscribed,true);
assert.equal((await apply({...state,signed_at:future(1),revoked_at:future(0)})).ignored,true);
const refund={...renewal,signed_at:future(2),revoked_at:future(1)};
assert.equal((await apply(refund)).subscribed,false);
assert.equal((await apply(renewal)).ignored,true);
assert.equal((await db.query('SELECT subscription_status FROM profiles')).rows[0].subscription_status,'free');
assert.equal((await apply({...refund,revoked_at:null})).ignored,true);
await assert.rejects(()=>apply({...state,product_id:null}),/Invalid verified/);
await assert.rejects(()=>apply({...state,environment:null}),/Invalid verified/);
assert.equal((await apply({...renewal,environment:'Sandbox',signed_at:future(3)})).ignored,true);
// An independent gift must survive the refund and keep editable preferences protected.
await db.query('UPDATE profiles SET premium_expires_at=$1,subscription_status=$2 WHERE user_id=$3',[future(90),'premium',id]);
await apply({...renewal,transaction_id:'t3',signed_at:future(4),expires_at:future(61)});
await apply({...renewal,transaction_id:'t3',signed_at:future(5),expires_at:future(61),revoked_at:future(5)});
assert.equal((await db.query('SELECT subscription_status FROM profiles')).rows[0].subscription_status,'premium');
await db.exec(`RESET ROLE; SET ROLE authenticated; SELECT set_config('request.jwt.claim.role','authenticated',false);`);
await db.query('UPDATE profiles SET preferences=$1 WHERE user_id=$2',[{theme:'red',apple_iap:{...state,expires_at:future(999)}},id]);
const pref=(await db.query('SELECT preferences FROM profiles')).rows[0].preferences;
assert.equal(pref.theme,'red');assert.notEqual(pref.apple_iap.expires_at,future(999));assert.ok(pref.apple_iap.revoked_at);
await db.exec(`RESET ROLE; SET ROLE service_role; SELECT set_config('request.jwt.claim.role','service_role',false);`);
await db.query('UPDATE profiles SET preferences=$1,premium_expires_at=NULL,subscription_status=$2 WHERE user_id=$3',[{theme:'blue'},'free',id]);
const stripe = async (active, observedAt=future(0)) => db.query('SELECT apply_stripe_plus_status($1,$2,$3,$4,$5)',[id,'cus_test',active,future(30),observedAt]);
await stripe(true);
await apply({...state, expires_at:future(60)});
await stripe(false,future(1));
assert.equal((await db.query('SELECT subscription_status FROM profiles')).rows[0].subscription_status,'premium');
await apply({...state, expires_at:future(60), signed_at:future(2), revoked_at:future(2)});
assert.equal((await db.query('SELECT subscription_status FROM profiles')).rows[0].subscription_status,'free');
await stripe(true,future(0));
assert.equal((await db.query('SELECT subscription_status FROM profiles')).rows[0].subscription_status,'free');
await db.exec(`RESET ROLE; SET ROLE authenticated; SELECT set_config('request.jwt.claim.role','authenticated',false);`);
await assert.rejects(()=>stripe(true),/permission denied/);
console.log('PASS: database permissions, forged metadata, renewal, older refund, restore replay, sandbox isolation, independent access, preference preservation and Stripe/Apple cancellation overlap');
await db.close();
