-- 20260420121000_seed_seo_content_startdata.sql
-- seed metadata only for seo content engine. no content, no summaries, no ai-generated text.

insert into public.seo_breeds (slug, name, breed_group, is_swedish_landrace, beginner_friendly, conservation_status, generation_status, published)
values
  ('hedemorahona', 'Hedemorahöna', 'lantras', true, true, 'hotad', 'pending', false),
  ('skansk-blommehona', 'Skånsk blommehöna', 'lantras', true, true, 'hotad', 'pending', false),
  ('bjurholmshona', 'Bjurholmshöna', 'lantras', true, false, 'akut hotad', 'pending', false),
  ('gammalsvensk-dvarghona', 'Gammalsvensk dvärghöna', 'lantras', true, true, 'hotad', 'pending', false),
  ('gotlandshona', 'Gotlandshöna', 'lantras', true, true, 'hotad', 'pending', false),
  ('halsingehona', 'Hälsingehöna', 'lantras', true, true, 'hotad', 'pending', false),
  ('kindahona', 'Kindahöna', 'lantras', true, true, 'hotad', 'pending', false),
  ('orusthona', 'Orusthöna', 'lantras', true, false, 'akut hotad', 'pending', false),
  ('olandshona', 'Ölandshöna', 'lantras', true, true, 'hotad', 'pending', false),
  ('asbohona', 'Åsbohöna', 'lantras', true, true, 'hotad', 'pending', false),
  ('leghorn', 'Leghorn', 'värpras', false, true, 'allmän', 'pending', false),
  ('lohmann-brown', 'Lohmann Brown', 'hybrid', false, true, 'allmän', 'pending', false),
  ('isa-brown', 'Isa Brown', 'hybrid', false, true, 'allmän', 'pending', false),
  ('bovans', 'Bovans', 'hybrid', false, true, 'allmän', 'pending', false),
  ('sussex', 'Sussex', 'dubbelnyttig', false, true, 'allmän', 'pending', false),
  ('orpington', 'Orpington', 'dubbelnyttig', false, true, 'allmän', 'pending', false),
  ('wyandotte', 'Wyandotte', 'dubbelnyttig', false, true, 'allmän', 'pending', false),
  ('plymouth-rock', 'Plymouth Rock', 'dubbelnyttig', false, true, 'allmän', 'pending', false),
  ('rhode-island-red', 'Rhode Island Red', 'dubbelnyttig', false, true, 'allmän', 'pending', false),
  ('marans', 'Marans', 'dubbelnyttig', false, true, 'allmän', 'pending', false),
  ('australorp', 'Australorp', 'dubbelnyttig', false, true, 'allmän', 'pending', false),
  ('brahma', 'Brahma', 'dubbelnyttig', false, false, 'allmän', 'pending', false),
  ('cochin', 'Cochin', 'dubbelnyttig', false, false, 'allmän', 'pending', false),
  ('silkehona', 'Silkehöna', 'dvärg', false, true, 'allmän', 'pending', false),
  ('sebright', 'Sebright', 'dvärg', false, false, 'allmän', 'pending', false),
  ('seramahona', 'Seramahöna', 'dvärg', false, false, 'allmän', 'pending', false),
  ('pekingbantam', 'Pekingbantam', 'dvärg', false, true, 'allmän', 'pending', false),
  ('araucana', 'Araucana', 'värpras', false, true, 'allmän', 'pending', false),
  ('cream-legbar', 'Cream Legbar', 'värpras', false, true, 'allmän', 'pending', false),
  ('welsummer', 'Welsummer', 'värpras', false, true, 'allmän', 'pending', false),
  ('ross-308', 'Ross 308', 'köttras', false, false, 'allmän', 'pending', false)
on conflict (slug) do update set
  name = excluded.name,
  breed_group = excluded.breed_group,
  is_swedish_landrace = excluded.is_swedish_landrace,
  beginner_friendly = excluded.beginner_friendly,
  conservation_status = excluded.conservation_status,
  generation_status = 'pending',
  published = false;

insert into public.seo_problems (slug, name, name_alt, category, severity, is_notifiable, is_zoonotic, generation_status, published)
values
  ('roda-kvalster', 'Röda kvalster', array['blodkvalster','Dermanyssus gallinae'], 'parasit', 'hög', false, false, 'pending', false),
  ('fjaderatande-loss', 'Fjäderätande löss', null, 'parasit', 'medel', false, false, 'pending', false),
  ('skabbkvalster', 'Skabbkvalster', null, 'parasit', 'medel', false, false, 'pending', false),
  ('luftrorsmask', 'Luftrörsmask', null, 'parasit', 'medel', false, false, 'pending', false),
  ('spolmask', 'Spolmask', null, 'parasit', 'medel', false, false, 'pending', false),
  ('bandmask', 'Bandmask hos höns', null, 'parasit', 'låg', false, false, 'pending', false),
  ('koccidios', 'Koccidios', null, 'parasit', 'hög', false, false, 'pending', false),
  ('fagelinfluensa', 'Fågelinfluensa', null, 'sjukdom', 'akut', true, true, 'pending', false),
  ('newcastlesjuka', 'Newcastlesjuka', null, 'sjukdom', 'akut', true, false, 'pending', false),
  ('marek', 'Marek', null, 'sjukdom', 'hög', false, false, 'pending', false),
  ('mykoplasma', 'Mykoplasma', null, 'sjukdom', 'medel', false, false, 'pending', false),
  ('infektios-bronkit', 'Infektiös bronkit', null, 'sjukdom', 'hög', false, false, 'pending', false),
  ('salmonella', 'Salmonella hos höns', null, 'sjukdom', 'hög', true, true, 'pending', false),
  ('rodsjuka', 'Rödsjuka', null, 'sjukdom', 'medel', false, false, 'pending', false),
  ('gumboro', 'Gumboro', null, 'sjukdom', 'hög', false, false, 'pending', false),
  ('krafthosta', 'Kräfthosta', null, 'sjukdom', 'medel', false, false, 'pending', false),
  ('hona-varper-inte', 'Höna värper inte', null, 'värpproblem', 'låg', false, false, 'pending', false),
  ('mjukskaliga-agg', 'Mjukskaliga ägg', null, 'värpproblem', 'medel', false, false, 'pending', false),
  ('aggstockning', 'Äggstockning', null, 'värpproblem', 'hög', false, false, 'pending', false),
  ('blod-i-aggen', 'Blod i äggen', null, 'värpproblem', 'låg', false, false, 'pending', false),
  ('dubbelgula-agg', 'Dubbelgula ägg', null, 'värpproblem', 'låg', false, false, 'pending', false),
  ('vinteruppehall-varpning', 'Vinteruppehåll i värpning', null, 'värpproblem', 'låg', false, false, 'pending', false),
  ('aggpickning', 'Äggpickning', null, 'beteende', 'medel', false, false, 'pending', false),
  ('fjaderpickning', 'Fjäderpickning', null, 'beteende', 'medel', false, false, 'pending', false),
  ('kannibalism', 'Kannibalism hos höns', null, 'beteende', 'hög', false, false, 'pending', false),
  ('ruvsjuka', 'Ruvsjuka (ruvbenägenhet)', null, 'beteende', 'låg', false, false, 'pending', false),
  ('aggressiv-tupp', 'Aggressiv tupp', null, 'beteende', 'medel', false, false, 'pending', false),
  ('integrering-nya-hons', 'Integrering av nya höns', null, 'beteende', 'medel', false, false, 'pending', false),
  ('overviktig-hona', 'Överviktig höna', null, 'näring', 'medel', false, false, 'pending', false),
  ('fettlever', 'Fettlever hos höns', null, 'näring', 'hög', false, false, 'pending', false),
  ('kalciumbrist', 'Kalciumbrist', null, 'näring', 'medel', false, false, 'pending', false),
  ('kropp-krava', 'Kropp kräva', null, 'näring', 'medel', false, false, 'pending', false),
  ('bumblefoot', 'Fotvårtor / Bumblefoot', array['bumblefoot'], 'skada', 'medel', false, false, 'pending', false),
  ('forfrysning-kammen', 'Förfrysning av kammen', null, 'skada', 'medel', false, false, 'pending', false),
  ('kloakprolaps', 'Kloakprolaps', null, 'skada', 'hög', false, false, 'pending', false),
  ('solsting', 'Solsting hos höns', null, 'skada', 'hög', false, false, 'pending', false),
  ('ruvning-vildmarken', 'Ruvning i vildmarken (förlorad höna)', null, 'skada', 'låg', false, false, 'pending', false)
on conflict (slug) do update set
  name = excluded.name,
  name_alt = excluded.name_alt,
  category = excluded.category,
  severity = excluded.severity,
  is_notifiable = excluded.is_notifiable,
  is_zoonotic = excluded.is_zoonotic,
  generation_status = 'pending',
  published = false;

insert into public.seo_care_topics (slug, name, category, generation_status, published)
values
  ('bygga-honshus-fran-scratch', 'Bygga hönshus från scratch', 'inhysning', 'pending', false),
  ('vinterhallning-av-hons', 'Vinterhållning av höns', 'inhysning', 'pending', false),
  ('sommarhallning-varmebolja', 'Sommarhållning i värmebölja', 'inhysning', 'pending', false),
  ('rengoring-av-honshus', 'Rengöring av hönshus', 'hygien', 'pending', false),
  ('vad-far-hons-ata', 'Vad får höns äta', 'utfodring', 'pending', false),
  ('vad-far-hons-inte-ata', 'Vad får höns INTE äta', 'utfodring', 'pending', false),
  ('integrera-nya-hons-i-flocken', 'Integrera nya höns i flocken', 'integration', 'pending', false),
  ('honshallning-regler-sverige', 'Hönshållning regler Sverige', 'lagar', 'pending', false),
  ('anmalningsplikt-honshallning-jordbruksverket', 'Anmälningsplikt hönshållning Jordbruksverket', 'lagar', 'pending', false),
  ('starta-med-hons-nyborjarguide', 'Starta med höns – nybörjarguide', 'nybörjare', 'pending', false),
  ('basta-honsrasen-for-nyborjare', 'Bästa hönsrasen för nybörjare', 'nybörjare', 'pending', false),
  ('hur-manga-hons-behover-man', 'Hur många höns behöver man', 'nybörjare', 'pending', false),
  ('rovdjursskydd-for-honsgard', 'Rovdjursskydd för hönsgård', 'inhysning', 'pending', false),
  ('honsgard-ytkrav', 'Hönsgård ytkrav', 'lagar', 'pending', false),
  ('avlivning-av-hona', 'Avlivning av höna', 'hygien', 'pending', false),
  ('flytta-hons-till-nytt-honshus', 'Flytta höns till nytt hönshus', 'integration', 'pending', false),
  ('foderautomat-och-vattenautomat', 'Foderautomat och vattenautomat', 'utfodring', 'pending', false),
  ('sandbad-for-hons', 'Sandbad för höns', 'hygien', 'pending', false),
  ('ljus-i-honshuset-vinter', 'Ljus i hönshuset på vintern', 'inhysning', 'pending', false),
  ('karantan-for-nya-hons', 'Karantän för nya höns', 'integration', 'pending', false)
on conflict (slug) do update set
  name = excluded.name,
  category = excluded.category,
  generation_status = 'pending',
  published = false;